### ISSUE TITLE
Make entry list smooth scrolling automatically disabled when the mod smooth scrolling refurbished is installed

### ISSUE THREAD

**Issue by handsome-steve** [SmajloSlovakian/Minecraft-Smooth-Scrolling#45] opened 2024-06-23 07:03 UTC
I've tested this with and without this mod, and basically;
While using Iris, Sodium along with Reese's Sodium Options, the mod breaks the scrollbar on the Shaders menu when using the scroll wheel on the mouse.
Otherwise, it seems to work fine just by dragging the scrollbar on the side, still however, I have had my friends request the Mod be removed from our modpack until it is fixed.

**Comment by SmajloSlovakian** [comment] 2024-06-23 08:23
i can't reproduce this issue on 1.20.6 with sodium-fabric-0.5.9+mc1.20.6, sodium-extra-0.5.6+mc1.20.6, iris-1.7.1+mc1.20.6, reeses_sodium_options-1.7.2+mc1.20.5-build.103 and smoothscroll-2.1.2-1.20.5... it works well for me and even scrolls smoothly (unlike the sodium options which just scroll)
can you please tell me, which versions of the mods and minecraft are you using?

**Comment by handsome-steve** [comment] 2024-06-23 09:28
1.21 Sorry, there was no option to select what version.
"Your mod version is the latest for 1.21"

>>> Mods are: <<<
sodium-fabric-0.5.9+mc1.21
sodium-extra-0.5.7+mc1.21
iris-1.7.1+mc1.21
reeses_sodium_options-1.7.2+mc1.21

>>> Potentially related mods: <<<
cloth-config-15.0.127-fabric
fabric-api-0.100.3+1.21

**Comment by SmajloSlovakian** [comment] 2024-06-23 09:39
still no luck in reproducing the issue... you will have to test if you can reproduce the issue with only the mentioned mods installed and if it does work as expected, you will have to test out which one of your mods in your modpack is causing the incompatibility... i suggest halving your mod list, testing, if it works then halving the other half of mods and trying that and so on... additionally, you can list all of your mods from the modpack in here

**Comment by handsome-steve** [comment] 2024-06-23 11:20
All good, I'll run through the mods and see what could be causing a conflict and I'll update.

**Comment by handsome-steve** [comment] 2024-06-23 12:00
Ok, so we've found the mod that is creating the conflict, on Modrinth it is called "[Smooth Scrolling Refurbished]"
( https://modrinth.com/mod/smooth-scrolling-refurbished )

File Version is:    SmoothScrollingRefurbished+1.21-1.1.4

I'll let the mod dev also know there may be an incompatibility with their mod and yours.

Also, their version of the smooth scroll on the Shader Packs page is a little nicer, thought I'd mention it in case you wanted to update your mod to match the scrolling, or remove/replace it so your mods can work hand in hand, up to you though 😃

**Comment by SmajloSlovakian** [comment] 2024-06-23 13:22
yeah i know of that mod... you can disable my version of smooth scrolling in the config file and iirc you can also distribute config file modifications through modpacks... to disable the feature in my mod for entry lists (the thing that mod touches), set entrylistspeed to 0 and everything should work correctly again...
i'll consider automatically disabling it when the user has both installed so the user doesn't end up confused...

**Comment by handsome-steve** [comment] 2024-06-23 13:29
Sounds good 😄

**Comment by SmajloSlovakian** [comment] 2024-09-01 10:10
resolved in update 2.1.3

**Closed as completed by SmajloSlovakian** 2024-09-01 10:10 UTC
Labels: bug, resolved in future update
