### ISSUE TITLE
Crash when scrolling command suggestions up and down fast

### ISSUE THREAD

**Issue by UninenVille** [SmajloSlovakian/Minecraft-Smooth-Scrolling#6] opened 2023-12-08 09:43 UTC
Steps to reproduce:
1. Create new world (or go into existing one, doesn't matter).
2. Open chat and type "/".
3. Start scrolling command suggestions up and down fast.
4. Game crashes

logs: https://mclo.gs/fazxTcw

**Comment by SmajloSlovakian** [comment] 2023-12-08 18:43
hmm.. i don't actually understand why exactly this happens... it may be because of some multithreading stuff but i don't know
it's easier to reproduce when you have a lower framerate... what you have to do is to scroll down and then quickly scroll up when the smooth scrolling didn't get to the target position yet... this should also be the case in the opposite way (on the end of the list)

i'm going to put a band aid solution in there, which will just not add any lines when it would crash... this means that there is still that garbage data but it will just work around it by not doing something stupid with it when it is garbage

**Comment by SmajloSlovakian** [comment] 2023-12-08 18:46
fixed by a workaround in 1.8.2

**Closed as completed by SmajloSlovakian** 2023-12-08 18:46 UTC
