### ISSUE TITLE
Some screens have a lower limit on scroll speed and it is dependant on framerate

### ISSUE THREAD

**Issue by MATRIX-feather** [SmajloSlovakian/Minecraft-Smooth-Scrolling#13] opened 2024-02-18 05:37 UTC
## Description
The chat scroll speed changes with the current game framerate:

https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/assets/55654482/0fc8bee0-b064-492a-a0e3-fe696c0b3f7b

## Expected behavior
Well... The scroll speed remains the same no matter what the framerate is

## Mods
Mods used in the video:
- Sodium
- Sodium Extra
- Blur
- Puzzle
- Immediately Fast
- ... and 66 more

This issue still presents with these mods installed:

- Fabric API
- Smooth Scroll

**Comment by SmajloSlovakian** [comment] 2024-02-19 11:15
hmmm... i can't really reproduce your issue as i don't have that much fps... i can see a small difference in speed on my pc but it certainly isn't as extreme as yours...
additionally, i do account for framerate changes in the code so it scrolls more in one frame if the duration of the last frame was long... sooo maybe there is a bug somewhere but it works at least partially as it should... gonna look at that

**Comment by SmajloSlovakian** [comment] 2024-02-19 11:23
ohh... i think i know why that happens... every frame it has to scroll by at least one pixel or nothing if the scroll position is at target... this is because i divide an offset which is an integer and can't have decimals so if i divide it by say 1.00000001 it shifts by one pixel no matter what... and so in your case it shifts by one pixel 800 times a second... i advice you to use your screen's refresh rate as this problem would take some effort to fix

**Comment by SmajloSlovakian** [comment] 2024-03-07 19:23
this issue will be fixed for multiple screens in version 1.9.0

**Closed by SmajloSlovakian** 2024-03-07 19:23 UTC

**Comment by MATRIX-feather** [comment] 2024-03-08 03:52
Thanks! ❤️
