### ISSUE TITLE
MouseY (at the drawing stage) position in containers before the creative inventory is opened is up at the top of the screen

### ISSUE THREAD

**Issue by ink5897** [SmajloSlovakian/Minecraft-Smooth-Scrolling#43] opened 2024-06-18 14:14 UTC
![ecf337b5-2dce-4084-9ea9-b197e3a060de](https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/assets/112875001/d56e2df6-c36e-4eb8-8d3a-8a07bd4dbc7f)

https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/assets/112875001/6ac70a68-e19e-4816-b47d-d9472894f714

To test this bug, I didn't add extra mods, only this one, but when I opened the game of 1,21, it was clear that when I opened the backpack, something went wrong

**Comment by LLLLLLeob** [comment] 2024-06-18 15:11
我也遇到了这个问题，禁用之后就没事了

**Comment by SmajloSlovakian** [comment] 2024-06-18 16:53
sorry, but i can't reproduce this issue. the launcher may be adding more modifications to the game that you don't know of. do you have any other minecraft launchers which you could try to test this out on?

**Comment by nickademas** [comment] 2024-06-18 20:35
![obraz](https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/assets/46594867/1b7e26ff-c15a-4050-b3f0-1a453b4b2544)

i have the same problem on prism launcher.

**Comment by SmajloSlovakian** [comment] 2024-06-19 06:36
okay, i have managed to reproduce this issue... steps to reproduce: don't open creative inventory before you do this, open the inventory and try to do things with items...
i'm going to fix this now

**Comment by SmajloSlovakian** [comment] 2024-06-19 07:23
fixed in 2.1.2

**Closed as completed by SmajloSlovakian** 2024-06-19 07:23 UTC
Labels: bug, resolved in future update
