### ISSUE TITLE
Chat disappears when using the mod

### ISSUE THREAD

**Issue by Taluch** [SmajloSlovakian/Minecraft-Smooth-Scrolling#50] opened 2024-08-15 17:15 UTC
whenever i use smoothscroll my chat doesn`t work and wont work no matter what i change in the settings

**Comment by SmajloSlovakian** [comment] 2024-08-15 20:05
do you use any other mods? which mods are you using and which mc version do you use?

**Comment by FoilGear** [comment] 2024-08-20 00:59
The chat disappears for me too. The cause as I have found is related to 'Chat Scale' in minecraft's chat settings.
If its value is somewhere below 0.96%, the chat clips from the top & ceases to be viewable.
*tested on MC version 1.21, fabric loader 0.16.2
Smooth Scroll 2.1.2
Fabric API 0.102.0+1.21
Fabric Language Kotlin 1.12.0+kotlin.2.0.10

**Comment by SmajloSlovakian** [comment] 2024-08-20 07:07
hmm that's an issue that...... exists... gonna try to fix it right away (although, idk if this is the issue for the op too, i would appreciate it if they replied)

**Comment by SmajloSlovakian** [comment] 2024-08-20 08:19
i think it's probable that they did have the same issue... so i'm going to mark this issue as resolved and if this is not the case for the op, they can comment on this issue...

**Comment by SmajloSlovakian** [comment] 2024-09-01 10:07
closing issue due to op not elaborating and another person elaborating with a very similar issue which is now resolved in update 2.1.3

**Closed as completed by SmajloSlovakian** 2024-09-01 10:07 UTC
Labels: bug, resolved in future update
